linters:
  presets:
    - metalinter
    - bugs
    - error
    - style
    - unused
    - performance
    - format
    - import
    - module
    - comment
    - test

  disable:
    - wrapcheck
    - exhaustivestruct
    - exhaustruct
    - gochecknoinits
    - gochecknoglobals
    - lll

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  nlreturn:
    block-size: 2
