name: "Ace Archive Artifact Action"
author: "Ace Archive"
description: >
  Query, validate, and rehost artifacts in Ace Archive.
inputs:
  path:
    description: >
      The path of the directory in the repository containing the artifact
      files.
    required: true
    default: "artifacts/"
  mode:
    description: >
      The mode to operate in, either `validate`, `history`, or `upload`. See
      the README for details.
    required: true
    default: "validate"
  ipfs-api:
    description: >
      The multiaddr of the API endpoint of the running IPFS node. This is
      required to upload artifacts to Web3.Storage or an IPFS pinning service.
    required: false
  w3s-token:
    description: >
      The secret API token for Web3.Storage. If this is provided, all artifacts
      in the repository are uploaded to Web3.Storage.
    required: false
  pin-endpoint:
    description: >
      The URL of the IPFS pinning service API endpoint to use. If this is
      provided, all artifacts in the repository are pinned using this pinning
      service.
    required: false
  pin-token:
    description: >
      The secret bearer token for the configured IPFS pinning service. This is
      required to pin artifacts using an IPFS pinning service.
    required: false
  dry-run:
    description: >
      Prevents uploading files when used in `upload` mode. Legal in other
      modes, but does nothing. Useful for testing.
    required: false
outputs:
  artifacts:
    description: >
      A JSON document describing the artifacts in the repository.
  cids:
    description: >
      A JSON array of the CIDs contained in artifacts in the repository,
      deduplicated by their multihash.
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--action"
branding:
  icon: "archive"
  color: "purple"
